name: miniDupe
version: '${project.version}'
main: me.minioof.minidupe_v2.miniDupe
api-version: 1.17
authors: [ 18o4 ]
description: minidupe but version 2
website: https://18o4.github.io

commands:
  dupe:
    description: a very basic command to give you the item you are holding
    usage: /<command>